# Use the official image as a parent image.
FROM node:current-slim

# Set the working directory
WORKDIR /usr/src/app

# Copy the file from your host to your current location.
COPY package.json

RUN npm install

EXPOSE 3000

CMD ["npm", "start"]