apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-chat-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-chat-app
  template:
    metadata:
      labels:
        app: demo-chat-app
    spec:
      containers:
      - image: cyaninn/demo-eks-cicd:15
        name: demo-chat-app
        ports:
        - containerPort: 3000
