apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-nginx-app
  template:
    metadata:
      labels:
        app: demo-nginx-app
    spec:
      containers:
      - image: cyaninn/demo-eks-cicd:latest
        name: demo-nginx-app
        ports:
        - containerPort: 80
